Repository terasolunaorg/terasoluna-tourreservation, pull requests merged in 2019-01, with the labels that each got.

#589 Update from Selenium 2 to Selenium 3 #573
  .travis.yml
  README.md
  pom.xml
  terasoluna-tourreservation-selenium/pom.xml
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/SystemErrorTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchPaginationTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchRegistValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnLogInTourSearchTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/WaitWebDriverEventListener.java
  terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/selenium.properties
  terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
Labels: priority: high, status: in-progress

#604 apply spring boot dependencies 2.1.2 #601 #602 #603 #588
  .travis.yml
  ISSUE_TEMPLATE.md
  pom.xml
  terasoluna-tourreservation-domain/pom.xml
  terasoluna-tourreservation-env/pom.xml
  terasoluna-tourreservation-initdb/pom.xml
  terasoluna-tourreservation-selenium/pom.xml
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/constants/MessageKeys.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
  terasoluna-tourreservation-selenium/src/test/resources/ValidationMessages_en.properties
  terasoluna-tourreservation-selenium/src/test/resources/ValidationMessages_ja.properties
  terasoluna-tourreservation-web/pom.xml
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managecustomer/CustomerForm.java
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/searchtour/SearchTourForm.java
  terasoluna-tourreservation-web/src/main/resources/ValidationMessages_en.properties
  terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties
Labels: status: in-progress, type: new-feature, version: 5.5.1

#606 fix build profile of terasoluna-gfw #602
  .travis.yml
Labels: status: in-progress, type: improvement, version: 5.5.1

#607 update selenium 3.14.0 + webdrivermanager 3.1.1 #571
  .travis.yml
  README.md
  pom.xml
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FirefoxDriverFactoryBean.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/FunctionTestSupport.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/WebDriverManagerFactoryBean.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/CustomerRegisterValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LanguageSwitchTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInLogOutTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/LogInReservUpdateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/SystemErrorTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchPaginationTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchRegistValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TourSearchValidateTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnLogInTourSearchTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/UnauthorizedAccessTest.java
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/WaitWebDriverEventListener.java
  terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/selenium.properties
  terasoluna-tourreservation-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
  terasoluna-tourreservation-selenium/src/test/resources/wdm.properties
Labels: status: in-progress, type: new-feature, version: 5.5.1
