Repository terasolunaorg/terasoluna-tourreservation, pull requests merged in 2019-03, with the labels that each got.

#608 [Spring 5.x] Dropped JasperReports support #582
  pom.xml
  terasoluna-tourreservation-domain/pom.xml
  terasoluna-tourreservation-web/pom.xml
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ReservationReportPdfStamperView.java
  terasoluna-tourreservation-web/src/main/resources/META-INF/spring/application.properties
  terasoluna-tourreservation-web/src/main/resources/META-INF/spring/spring-mvc.xml
  terasoluna-tourreservation-web/src/main/resources/reports/reservationReport.pdf
  terasoluna-tourreservation-web/src/main/webapp/WEB-INF/reports/reservationReportPdf.jrxml
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
Labels: status: in-progress, type: new-feature, version: 5.5.1

#613 update jdbc driver #612
  pom.xml
Labels: status: in-progress

#611 add Unit Test #582
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ReservationReportPdfStamperView.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ReservationReportPdfStamperViewTest.java
Labels: status: in-progress, type: new-feature, version: 5.5.1

#615 resolve deprecated api #614
  terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/common/constants/MessageKeysGen.java
  terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationControllerTest.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/reservetour/ReserveTourHelperTest.java
  terasoluna-tourreservation-web/src/test/java/org/terasoluna/tourreservation/app/searchtour/SearchTourControllerTest.java
Labels: status: in-progress, type: improvement, version: 5.5.1
